POST /add_theoretical_grade/Advanced English II?username=s172327
Host: localhost:8000
Content-Type: application/json

{
    "name": "Whoopsies",
    "category": "Homework",
    "weight": 20.0,
    "score": 0
}